$(function(){
    // $("#container").css("background-color","yellow");
    $(".pro1").click(function(){
        $(".info").animate({right:'20px'});
        $(".info1").animate({right:'-1000px'});
        $(".info2").animate({right:'-1000px'})
    });
    $(".cancel1").click(function(){
        $(".info").animate({right:'20px'});
        $(".info1").animate({right:'-1000px'});
        $(".info2").animate({right:'-1000px'});
    });
    $(".sure").click(function(){
        $(".info").animate({right:'-1000px'});
        $(".info1").animate({right:'20px'});
        $(".info2").animate({right:'-1000px'});
    });
    $(".sure1").click(function(){
        $(".info").animate({right:'-1000px'});
        $(".info2").animate({right:'20px'});
        $(".info1").animate({right:'-1000px'});
    });
    $(".cancel2").click(function(){
        $(".info").animate({right:'-1000px'});
        $(".info1").animate({right:'20px'});
        $(".info2").animate({right:'-1000px'});
    });
});